
public class mainClass {
	 public static void main(String[] args) { //Main class will display the output of all employees, using the data from the other classes 
	
		 SoftwareEngineer Hank = new SoftwareEngineer();
		 Hank.setName("Hank");
		 Hank.setAge(27);
		 Hank.setRank(1);
		 Hank.setProg(1);
		 Hank.setComp("Microsoft");
		 Hank.personData();
		 Hank.employeeData();
		 Manager Terry = new Manager();
		 Terry.setName("Terry");
		 Terry.setAge(35);
		 Terry.setSpec(1);
		 Terry.setComp("Oracle");
		 Terry.personData();
		 Terry.employeeData();
		 Intern Mario = new Intern();
		 Mario.setName("Mario");
		 Mario.setAge(19);
		 Mario.setDuty("Programmer");
		 Mario.setComp("Oracle");
		 Mario.personData();
		 Mario.employeeData();
		 administrator Paula = new administrator();
		 Paula.setName("Paula");
		 Paula.setAge(25);
		 Paula.setComp("Google");
		 Paula.setType(1);
		 Paula.personData();
		 Paula.employeeData();
		 Security Danilo = new Security();
		 Danilo.setName("Danilo");
		 Danilo.setAge(29);
		 Danilo.setComp("Google");
		 Danilo.setPos("Security Guard");
		 Danilo.personData();
		 Danilo.employeeData();
		 administrator Barry = new administrator();
		 Barry.setName("Barry");
		 Barry.setAge(23);
		 Barry.setComp("KPMG");
		 Barry.setType(2);
		 Barry.personData();
		 Barry.employeeData();
		 SoftwareEngineer Peyton = new SoftwareEngineer();
		 Peyton.setName("Peyton");
		 Peyton.setAge(26);
		 Peyton.setComp("KPMG");
		 Peyton.setProg(3);
		 Peyton.setRank(2);
		 Peyton.personData();
		 Peyton.employeeData();
		 Security Wayne = new Security();
		 Wayne.setName("Wayne");
		 Wayne.setAge(30);
		 Wayne.setPos("Cyber-Security");
		 Wayne.setComp("KPMG");
		 Wayne.personData();
		 Wayne.employeeData();
		 Manager Phil = new Manager();
		 Phil.setName("Phil");
		 Phil.setAge(37);
		 Phil.setCompany("KPMG");
		 Phil.setSpec(2);
		 Phil.personData();
		 Phil.employeeData();
		 SoftwareEngineer Carlos = new SoftwareEngineer();
		 Carlos.setName("Carlos");
		 Carlos.setAge(22);
		 Carlos.setComp("Valve");
		 Carlos.setProg(3);
		 Carlos.setRank(1);
		 Carlos.personData();
		 Carlos.employeeData();
	}
}
